### ISSUE TITLE
osdlabs.github.io/blog.html should redirect here

### ISSUE THREAD

**Issue by kaivalyar** [OSDLabs/blog#2]
`<body onload="javascipt: window.location='http://blog.osdlabs.org'"></body>` should do the trick.

**Comment by SebastinSanty** [comment]
Done :)

**Comment by SebastinSanty** [comment]
I assume it is safe to close

**Comment by mukkachaitanya** [comment]
The `osdlabs.org/blog.html` is loaded before `blog.osdlabs.org` is loaded. This isn't desirable.
